### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by tokra100**
Added code for __init__.py

### CODE REVIEW

**Comment by mmerickel** [comment]
I'm sorry but this PR looks exactly like the code in `__init__.py` already, and you took it out and placed it directly in the docs. Can you explain what you're trying to fix here?

**Comment by tokra100** [comment]
Yeah. If you take a look at http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/06-template/index.html, there is missing something at the first "2.".
I only see "Since we are using Chameleon, tutorial/__init__.py needs an additional configuration:", but the code is missing. Sorry, when i messed it up :\

**Comment by mmerickel** [comment]
Ok, I see now. We don't want to lose the literalinclude if don't have to. Presumably there's just a syntax issue preventing it from showing up the way we want.

**Comment by mmerickel** [comment]
The bullet #2 at http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/05-tests/index.html is using a literalinclude. There is a bit more whitespace around it which is probably what we're missing here.

**Comment by tokra100** [comment]
Okay :+1:

**Comment by stevepiercy** [comment]
Closed by #87

**Pull request closed without merging**
